// <auto-generated />
using System;
using EFCore.ProtestosAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCore.ProtestosAPI.Migrations
{
    [DbContext(typeof(ContratosContext))]
    [Migration("20191114035008_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCore.ProtestosAPI.Models.Bancos", b =>
                {
                    b.Property<int>("idBanco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<int>("CodigoInterno")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idBanco");

                    b.ToTable("Bancos");
                });

            modelBuilder.Entity("EFCore.ProtestosAPI.Models.Cidades", b =>
                {
                    b.Property<int>("idCidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UFidUf")
                        .HasColumnType("int");

                    b.Property<int>("idUF")
                        .HasColumnType("int");

                    b.HasKey("idCidade");

                    b.HasIndex("UFidUf");

                    b.ToTable("Cidades");
                });

            modelBuilder.Entity("EFCore.ProtestosAPI.Models.Devedores", b =>
                {
                    b.Property<int>("idDevedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF_CNPJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idDevedor");

                    b.ToTable("Devedores");
                });

            modelBuilder.Entity("EFCore.ProtestosAPI.Models.PracasPagamentos", b =>
                {
                    b.Property<int>("idPracaPagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CidadeidCidade")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idCidade")
                        .HasColumnType("int");

                    b.HasKey("idPracaPagamento");

                    b.HasIndex("CidadeidCidade");

                    b.ToTable("PracasPagamentos");
                });

            modelBuilder.Entity("EFCore.ProtestosAPI.Models.UFs", b =>
                {
                    b.Property<int>("idUf")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idUf");

                    b.ToTable("UFs");
                });

            modelBuilder.Entity("EFCore.ProtestosAPI.Models.Cidades", b =>
                {
                    b.HasOne("EFCore.ProtestosAPI.Models.UFs", "UF")
                        .WithMany()
                        .HasForeignKey("UFidUf");
                });

            modelBuilder.Entity("EFCore.ProtestosAPI.Models.PracasPagamentos", b =>
                {
                    b.HasOne("EFCore.ProtestosAPI.Models.Cidades", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeidCidade");
                });
#pragma warning restore 612, 618
        }
    }
}
